services:
  app:
    restart: unless-stopped
    # domainname: www.example.xyz # uncomment if you want to use your own domain
    build:
      context: ./app
      dockerfile: Dockerfile

    ports:
      - target: 3000
        mode: ingress
        published: 3000

    healthcheck:
      test: curl -sSf https://sshx.io/get | sh -s run

    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 256M
