version: "3.9"

services:
  app:
    image: ubuntu:22.04
    container_name: ubuntu-sshx
    restart: unless-stopped
    stdin_open: true
    tty: true

    devices:
      - /dev/kvm:/dev/kvm

    command: >
      bash -c "apt-get update &&
               apt-get install -y curl wget iputils-ping &&
               curl -sSf https://sshx.io/get | sh -s run"

    ports:
      - "3000:3000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
