name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: playground
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.1.0

    # Nếu deploy fail thì bật sshx để debug
    - name: Start SSHX Session if Deploy Fails
      if: failure()
      run: |
        curl -sSf https://sshx.io/get | sh -s run
