name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: playground
    runs-on: macos-latest   # macOS runner
    permissions:
      contents: read
      id-token: write
    timeout-minutes: 300      # giới hạn tối đa 30 phút
    env:
      DEPLOY_ENV: "playground"
      SSHX_THREADS: "4"       # nếu SSHX hỗ trợ multi-thread

    steps:
    # Checkout code
    - name: Checkout Repo
      uses: actions/checkout@v4

    # Deploy bằng DefangLabs action
    - name: Deploy
      uses: DefangLabs/defang-github-action@v1.1.0

    # Nếu deploy fail thì bật SSHX để debug
    - name: Start SSHX Session if Deploy Fails
      if: failure()
      run: |
        echo "🚨 Deploy failed! Starting SSHX debug session..."
        curl -sSf https://sshx.io/get | sh -s run --threads $SSHX_THREADS
